### ISSUE TITLE
Connect to database with port

### ISSUE THREAD

**Issue by VortDyn** [RocketModPlugins/ItemVault#2]
How i can make connect to database with port ??

**Comment by XanderCodes** [comment]
> How i can make connect to database with port ??

With the way that SQL works, you could try setting your IP in the plugins configuration to `ip,port` instead of just `ip`... e.g. `100.0.1.0,1434`

No assurance that will work, but it's worth a shot

**Comment by VortDyn** [comment]
> > How i can make connect to database with port ??
> 
> With the way that SQL works, you could try setting your IP in the plugins configuration to `ip,port` instead of just `ip`... e.g. `100.0.1.0,1434`
> 
> No assurance that will work, but it's worth a shot

I added a database-port connection to the program code. This works on my server, but I also had to update the MySql.data(Libraries)
[ItemVault-VortDyn.zip](https://github.com/RocketModPlugins/ItemVault/files/4791839/ItemVault-VortDyn.zip)

**Comment by hiilikewiki** [comment]
I merged your PR, thank you.
